/** @format */

export interface EcsAgentScriptOptions {
  clusterName: string;
  dockerMaxRetries: number;
  dockerRetryDelaySeconds: number;
  ecsStartMaxRetries: number;
  ecsStartRetryDelaySeconds: number;
  agentCheckMaxRetries: number;
  agentCheckDelaySeconds: number;
}

/**
 * Build ECS agent configuration script with tunable retry settings.
 */
export function buildEcsAgentScript(options: EcsAgentScriptOptions): string {
  const {
    clusterName,
    dockerMaxRetries,
    dockerRetryDelaySeconds,
    ecsStartMaxRetries,
    ecsStartRetryDelaySeconds,
    agentCheckMaxRetries,
    agentCheckDelaySeconds,
  } = options;

  return [
    "#!/bin/bash",
    "# Don't use 'set -e' - we want to handle errors gracefully",
    "set -o pipefail",
    "",
    "echo '========================================='",
    "echo 'ECS Agent Configuration Script'",
    "echo 'Timestamp:' $(date)",
    "echo '========================================='",
    "",
    "# Configure ECS cluster (idempotent - safe to run multiple times)",
    `echo ECS_CLUSTER=${clusterName} >> /etc/ecs/ecs.config || echo 'WARNING: Failed to write ECS_CLUSTER'`,
    "echo ECS_ENABLE_CONTAINER_METADATA=true >> /etc/ecs/ecs.config || true",
    "echo ECS_ENABLE_TASK_IAM_ROLE=true >> /etc/ecs/ecs.config || true",
    "echo ECS_AWSVPC_BLOCK_IMDS=true >> /etc/ecs/ecs.config || true",
    "cat >> /etc/ecs/ecs.config << 'EOF' || true",
    'ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs"]',
    "EOF",
    "",
    "# Verify the config was written correctly",
    "echo 'Verifying ECS config format...'",
    "if grep -q 'ECS_AVAILABLE_LOGGING_DRIVERS' /etc/ecs/ecs.config; then",
    "  echo '✓ ECS_AVAILABLE_LOGGING_DRIVERS found in config'",
    "  grep 'ECS_AVAILABLE_LOGGING_DRIVERS' /etc/ecs/ecs.config",
    "else",
    "  echo 'WARNING: ECS_AVAILABLE_LOGGING_DRIVERS not found in config'",
    "fi",
    "",
    "# Ensure Docker is running (required for ECS agent on AL2023)",
    "echo 'Ensuring Docker is running...'",
    "systemctl enable docker 2>&1 || echo 'WARNING: Failed to enable Docker'",
    "systemctl start docker 2>&1 || echo 'WARNING: Failed to start Docker'",
    "",
    "# Wait for Docker to be ready",
    "echo 'Waiting for Docker to be ready...'",
    "DOCKER_RETRY=0",
    `DOCKER_MAX_RETRIES=${dockerMaxRetries}`,
    "DOCKER_READY=false",
    "while [ $DOCKER_RETRY -lt $DOCKER_MAX_RETRIES ]; do",
    "  if systemctl is-active docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then",
    "    echo 'Docker is ready'",
    "    DOCKER_READY=true",
    "    break",
    "  fi",
    "  DOCKER_RETRY=$((DOCKER_RETRY + 1))",
    '  echo "Waiting for Docker (attempt $DOCKER_RETRY/$DOCKER_MAX_RETRIES)..."',
    "  systemctl start docker >/dev/null 2>&1 || true",
    `  sleep ${dockerRetryDelaySeconds}`,
    "done",
    "",
    'if [ "$DOCKER_READY" != "true" ]; then',
    "  echo 'WARNING: Docker not ready after $DOCKER_MAX_RETRIES attempts, continuing anyway'",
    "fi",
    "",
    "# Pre-pull ECS agent Docker image",
    "echo 'Pre-pulling ECS agent Docker image...'",
    'ECS_AGENT_IMAGE="public.ecr.aws/ecs/amazon-ecs-agent:latest"',
    'ECS_AGENT_LEGACY_TAG="amazon/amazon-ecs-agent:latest"',
    "if command -v docker >/dev/null 2>&1; then",
    "  if docker info >/dev/null 2>&1; then",
    '    echo "Pulling ECS agent image: $ECS_AGENT_IMAGE"',
    "    docker pull $ECS_AGENT_IMAGE 2>&1 || echo 'WARNING: Failed to pull ECS agent image'",
    "    if docker images | grep -q amazon-ecs-agent; then",
    '      echo "Creating legacy tag alias: $ECS_AGENT_LEGACY_TAG"',
    "      docker tag $ECS_AGENT_IMAGE $ECS_AGENT_LEGACY_TAG 2>&1 || echo 'WARNING: Failed to create legacy tag'",
    "    fi",
    "  else",
    "    echo 'WARNING: Docker daemon not accessible, skipping image pull'",
    "  fi",
    "else",
    "  echo 'WARNING: Docker command not found'",
    "fi",
    "",
    "# Configure ECS agent service with retry logic (idempotent)",
    "echo 'Configuring ECS agent service...'",
    "mkdir -p /etc/systemd/system/ecs.service.d",
    "cat > /etc/systemd/system/ecs.service.d/override.conf << 'EOF' || echo 'WARNING: Failed to create override.conf'",
    "[Service]",
    "Restart=on-failure",
    "RestartSec=30",
    "StartLimitInterval=600",
    "StartLimitBurst=20",
    "EOF",
    "systemctl daemon-reload || echo 'WARNING: Failed to reload systemd'",
    "",
    "# Start/Restart ECS agent to pick up new logging drivers config",
    "echo 'Starting/Restarting ECS agent to apply logging drivers config...'",
    "systemctl enable ecs 2>&1 || echo 'WARNING: Failed to enable ECS service'",
    "systemctl reset-failed ecs 2>&1 || true",
    "",
    "# Restart ECS agent if already running to pick up config changes",
    "if systemctl is-active ecs >/dev/null 2>&1; then",
    "  echo 'ECS agent is running, restarting to apply new logging drivers config...'",
    "  systemctl restart ecs 2>&1 || echo 'WARNING: Failed to restart ECS service'",
    "else",
    "  echo 'ECS agent not running, starting...'",
    "fi",
    "",
    "# Start ECS agent with retries",
    "ECS_START_RETRY=0",
    `ECS_START_MAX_RETRIES=${ecsStartMaxRetries}`,
    "ECS_STARTED=false",
    "while [ $ECS_START_RETRY -lt $ECS_START_MAX_RETRIES ]; do",
    "  if systemctl start ecs 2>&1; then",
    "    echo 'ECS service start command succeeded'",
    "    ECS_STARTED=true",
    "    break",
    "  fi",
    "  ECS_START_RETRY=$((ECS_START_RETRY + 1))",
    '  echo "ECS start attempt $ECS_START_RETRY/$ECS_START_MAX_RETRIES failed, retrying..."',
    "  systemctl reset-failed ecs 2>&1 || true",
    `  sleep ${ecsStartRetryDelaySeconds}`,
    "done",
    "",
    'if [ "$ECS_STARTED" != "true" ]; then',
    "  echo 'WARNING: Failed to start ECS service after $ECS_START_MAX_RETRIES attempts'",
    "  echo 'Checking if ECS agent is already running...'",
    "fi",
    "",
    "# Verify ECS agent is running",
    "echo 'Verifying ECS agent is running...'",
    "RETRY_COUNT=0",
    `MAX_RETRIES=${agentCheckMaxRetries}`,
    "AGENT_RUNNING=false",
    "",
    "while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do",
    "  if pgrep -f 'ecs-agent' >/dev/null 2>&1; then",
    "    echo 'ECS agent process detected'",
    "    if [ -f /var/log/ecs/ecs-agent.log ]; then",
    "      AGENT_PID=$(pgrep -f 'ecs-agent' | head -1)",
    '      if [ -n "$AGENT_PID" ]; then',
    '        if [ -d "/proc/$AGENT_PID" ]; then',
    "          AGENT_START_TIME=$(stat -c %Y /proc/$AGENT_PID 2>/dev/null || echo 0)",
    "          CURRENT_TIME=$(date +%s)",
    "          AGENT_UPTIME=$((CURRENT_TIME - AGENT_START_TIME))",
    "          if [ $AGENT_UPTIME -ge 10 ]; then",
    "            echo 'ECS agent is running and stable (uptime: ${AGENT_UPTIME}s)'",
    "            AGENT_RUNNING=true",
    "            break",
    "          else",
    '            echo "ECS agent starting (uptime: ${AGENT_UPTIME}s), waiting for stabilization..."',
    "          fi",
    "        else",
    "          echo 'ECS agent process is running'",
    "          AGENT_RUNNING=true",
    "          break",
    "        fi",
    "      fi",
    "    else",
    "      echo 'ECS agent process running but log file not found, waiting...'",
    "    fi",
    "  else",
    "    if [ $RETRY_COUNT -gt 0 ] && [ $((RETRY_COUNT % 6)) -eq 0 ]; then",
    "      echo 'Retrying ECS agent start...'",
    "      systemctl reset-failed ecs 2>&1 || true",
    "      systemctl start ecs 2>&1 || true",
    "    fi",
    "  fi",
    "",
    "  RETRY_COUNT=$((RETRY_COUNT + 1))",
    "  if [ $((RETRY_COUNT % 6)) -eq 0 ]; then",
    '    echo "Still waiting for ECS agent (attempt $RETRY_COUNT/$MAX_RETRIES)..."',
    "  fi",
    `  sleep ${agentCheckDelaySeconds}`,
    "done",
    "",
    "if [ \"$AGENT_RUNNING\" = \"true\" ]; then",
    "  echo '========================================='",
    "  echo 'SUCCESS: ECS agent is running and stable'",
    "  echo '========================================='",
    "  exit 0",
    "else",
    "  echo '========================================='",
    "  echo 'WARNING: ECS agent not confirmed running after $MAX_RETRIES attempts'",
    "  echo 'This may be normal if the agent is still starting or if IAM/network dependencies are pending.'",
    "  echo '========================================='",
    "  exit 0",
    "fi",
  ].join("\n");
}
